### ISSUE TITLE
IndexError at initialization of SemanticLoss : list index out of range

### ISSUE THREAD

**Issue by LedaguenelArthur** [lucadiliello/semantic-loss-pytorch#4]
Hi,

I have been conducting simple tests with the semantic loss package and I got an unexpected error.
I am working with constraints encoded in a **ex1.sympy** file.

Following the steps in the README of this repository, I converted the constraints into DIMACS format **ex1_dimacs.txt** and then compiled the vtree **ex1.vtree** and the sdd **ex1.sdd** using PySDD.

But then when I try to initialize the semantic loss object with the resulting files with :
`sl = SemanticLoss('ex1.sdd', 'ex1.vtree')`

I get the following error :
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
c:\Users\arthur.ledaguenel\Documents\Experiences\NeSy\example1.ipynb Cellule 26 in <cell line: 1>()
----> [1](vscode-notebook-cell:/c%3A/Users/arthur.ledaguenel/Documents/Experiences/NeSy/example1.ipynb#X65sZmlsZQ%3D%3D?line=0) sl = SemanticLoss('ex1.sdd', 'ex1.vtree')

File c:\Users\arthur.ledaguenel\Documents\Experiences\NeSy\semantic_loss_pytorch\semantic_loss.py:47, in SemanticLoss.__init__(self, sdd_file, vtree_file, *args, **kwargs)
     45 super().__init__(*args, **kwargs)
     46 # instantiate the psdd
---> 47 self.psdd = SemanticLoss._import_psdd(sdd_file, vtree_file)

File c:\Users\arthur.ledaguenel\Documents\Experiences\NeSy\semantic_loss_pytorch\semantic_loss.py:36, in SemanticLoss._import_psdd(sdd_file, vtree_file)
     33 assert os.path.isfile(vtree_file), f"{vtree_file} is not a file."
     35 # load vtree and sdd files and construct the PSDD
---> 36 vtree = Vtree.read(vtree_file)
     37 manager = SddManager(vtree)
     38 alpha = io.sdd_read(sdd_file, manager)

File c:\Users\arthur.ledaguenel\Documents\Experiences\NeSy\semantic_loss_pytorch\py3psdd\vtree.py:133, in Vtree.read(filename)
    131 line = line[2:].split() # skip "I" and split
    132 node_id,left_id,right_id = [int(x) for x in line]
--> 133 left,right = nodes[left_id],nodes[right_id]
    134 node = Vtree.internal_node(left,right)
    135 left.parent = right.parent = node

IndexError: list index out of range
```

Did i do something wrong during compilation ? Is there a way to solve it ?

The dimacs file is attached here :
[ex1_dimacs.txt](https://github.com/lucadiliello/semantic-loss-pytorch/files/10732022/ex1_dimacs.txt)

Best regards,
Arthur

**Comment by lucadiliello** [comment]
Can you share the original `ex1.sympy` file?

**Comment by LedaguenelArthur** [comment]
Here is the original `ex1.sympy` file :

```
shape [5]
X0 | ~X1
X0 | ~X2
~X1 | ~X2
X1 | ~X3
X1 | ~X4
~X3 | ~X4
```

**Comment by lucadiliello** [comment]
I cannot reproduce your bug, can you share the version of the main packages you are using such as `python`, `numpy` and `torch`?

**Comment by LedaguenelArthur** [comment]
Here are the versions I am using :
python 3.10.4
numpy 1.22.3
torch 1.11.0

**Comment by LedaguenelArthur** [comment]
ex1.vtree :

```
c ids of vtree nodes start at 0
c ids of variables start at 1
c vtree nodes appear bottom-up, children before parents
c
c file syntax:
c vtree number-of-nodes-in-vtree
c L id-of-leaf-vtree-node id-of-variable
c I id-of-internal-vtree-node id-of-left-child id-of-right-child
c
vtree 9
L 0 2
L 2 3
L 4 1
L 6 4
L 8 5
I 7 6 1516123455496
I 5 4 1516123455495
I 3 2 1516123455493
I 1 0 1516123455491
```

**Comment by LedaguenelArthur** [comment]
**ex1.sdd** :

```
c ids of sdd nodes start at 0
c sdd nodes appear bottom-up, children before parents
c
c file syntax:
c sdd count-of-sdd-nodes
c F id-of-false-sdd-node
c T id-of-true-sdd-node
c L id-of-literal-sdd-node id-of-vtree literal
c D id-of-decomposition-sdd-node id-of-vtree number-of-elements {id-of-prime id-of-sub}*
c
sdd 18
L 1 0 -2
L 3 2 3
L 5 4 1
L 7 6 -4
L 8 8 -5
L 9 6 4
F 10
D 6 7 2 7 8 9 10
L 11 4 -1
D 4 5 2 5 6 11 10
L 12 2 -3
D 2 3 2 3 4 12 6
L 13 0 2
T 17
D 16 7 2 9 8 7 17
D 15 5 2 5 16 11 10
D 14 3 2 12 15 3 10
D 0 1 2 1 2 13 14
```

**Comment by lucadiliello** [comment]
I was able to load the `sdd` and the `vtree` with `torch==1.13.1`, `numpy==1.24.2` and `python==3.9.12`.

**Comment by LedaguenelArthur** [comment]
Hi @lucadiliello,

I have tried with your specific config but I still can't make it work...

Here is my conda environnement set up :
```
(base) C:\Users\arthur.ledaguenel>conda list -n test
# packages in environment at C:\Users\arthur.ledaguenel\Miniconda3\envs\test:
#
# Name                    Version                   Build  Channel
ca-certificates           2023.01.10           haa95532_0
certifi                   2022.12.7        py39haa95532_0
numpy                     1.24.2                   pypi_0    pypi
openssl                   1.1.1t               h2bbff1b_0
pip                       23.0.1           py39haa95532_0
python                    3.9.12               h6244533_0
setuptools                65.6.3           py39haa95532_0
sqlite                    3.41.1               h2bbff1b_0
torch                     1.13.1                   pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2022g                h04d1e81_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.38.4           py39haa95532_0
wincertstore              0.2              py39haa95532_2
```

Here's the **test.py** script I'm trying to execute :
```
from semantic_loss_pytorch import SemanticLoss
import sys
print(sys.version)

sl = SemanticLoss('./ex1.sdd', './ex1.vtree')
```

Here's the error I get when executing :
```
(test) C:\Users\arthur.ledaguenel\Documents\Experiences\NeSy>python test.py
3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Traceback (most recent call last):
  File "C:\Users\arthur.ledaguenel\Documents\Experiences\NeSy\test.py", line 5, in <module>
    sl = SemanticLoss('./ex1.sdd', './ex1.vtree')
  File "C:\Users\arthur.ledaguenel\Documents\Experiences\NeSy\semantic_loss_pytorch\semantic_loss.py", line 47, in __init__
    self.psdd = SemanticLoss._import_psdd(sdd_file, vtree_file)
  File "C:\Users\arthur.ledaguenel\Documents\Experiences\NeSy\semantic_loss_pytorch\semantic_loss.py", line 36, in _import_psdd
    vtree = Vtree.read(vtree_file)
  File "C:\Users\arthur.ledaguenel\Documents\Experiences\NeSy\semantic_loss_pytorch\py3psdd\vtree.py", line 133, in read
    left,right = nodes[left_id],nodes[right_id]
IndexError: list index out of range
```

Is there any thing else that could explain this error ?

**Comment by lucadiliello** [comment]
I still cannot reproduce your error. Were you able to solve it?
